 steps:
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
   secretEnv: ['USERNAME', 'PASSWORD']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker build -t $$USERNAME/pylon:1.0.2 .']
   secretEnv: ['USERNAME']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker image tag $$USERNAME/pylon:1.0.2 $$USERNAME/pylon:latest']
   secretEnv: ['USERNAME']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker push $$USERNAME/pylon:latest']
   secretEnv: ['USERNAME']
 availableSecrets:
   secretManager:
   - versionName: projects/misc-zhardie/secrets/dockerhub_password/versions/1
     env: 'PASSWORD'
   - versionName: projects/misc-zhardie/secrets/dockerhub_username/versions/2
     env: 'USERNAME'